# Generated by Django 5.2.7 on 2025-10-14 01:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="FoundProduct",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("reporter_name", models.CharField(max_length=100)),
                ("email", models.EmailField(blank=True, max_length=254, null=True)),
                (
                    "image",
                    models.ImageField(
                        blank=True, null=True, upload_to="found_product_images/"
                    ),
                ),
                ("reporter_contact", models.CharField(max_length=100)),
                ("report_date", models.DateTimeField(auto_now_add=True)),
                ("additional_info", models.TextField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "Product Found Report",
                "verbose_name_plural": "Product Found Reports",
                "ordering": ["-report_date"],
            },
        ),
        migrations.CreateModel(
            name="LostProduct",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("reporter_name", models.CharField(max_length=100)),
                ("reporter_contact", models.CharField(max_length=100)),
                ("email", models.EmailField(blank=True, max_length=254, null=True)),
                (
                    "image",
                    models.ImageField(
                        blank=True, null=True, upload_to="lost_product_images/"
                    ),
                ),
                ("report_date", models.DateTimeField(auto_now_add=True)),
                ("additional_info", models.TextField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "Product Lost Report",
                "verbose_name_plural": "Product Lost Reports",
                "ordering": ["-report_date"],
            },
        ),
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("user", models.CharField(max_length=100)),
                ("message", models.TextField()),
                ("is_read", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Product Notification",
                "verbose_name_plural": "Product Notifications",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField()),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("Electronics", "Electronics"),
                            ("Clothing", "Clothing"),
                            ("Stationery", "Stationery"),
                            ("Other", "Other"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("Lost", "Lost"), ("Found", "Found")], max_length=10
                    ),
                ),
                ("location", models.CharField(max_length=255)),
                ("date_reported", models.DateTimeField()),
                (
                    "deleted_status",
                    models.IntegerField(
                        choices=[(1, "Live"), (0, "Inactive")], default=1
                    ),
                ),
                ("image", models.ImageField(blank=True, null=True, upload_to="media/")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Product",
                "verbose_name_plural": "Products",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="MatchResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("lost_embedding", models.BinaryField(blank=True, null=True)),
                ("found_embedding", models.BinaryField(blank=True, null=True)),
                ("similarity_score", models.FloatField()),
                ("match_status", models.CharField(max_length=50)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "found_product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="match_results",
                        to="Product.foundproduct",
                    ),
                ),
                (
                    "lost_product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="match_results",
                        to="Product.lostproduct",
                    ),
                ),
            ],
            options={
                "verbose_name": "Product Match Result",
                "verbose_name_plural": "Product Match Results",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddField(
            model_name="lostproduct",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="lost_reports",
                to="Product.product",
            ),
        ),
        migrations.AddField(
            model_name="foundproduct",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="found_reports",
                to="Product.product",
            ),
        ),
        migrations.CreateModel(
            name="ProductImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="product_images/")),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="Product.product",
                    ),
                ),
            ],
            options={
                "verbose_name": "Product Image",
                "verbose_name_plural": "Product Images",
                "ordering": ["-uploaded_at"],
            },
        ),
        migrations.CreateModel(
            name="RouteMap",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("map_image", models.ImageField(upload_to="route_maps/")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="route_maps",
                        to="Product.product",
                    ),
                ),
            ],
            options={
                "verbose_name": "Product Route Map",
                "verbose_name_plural": "Product Route Maps",
                "ordering": ["-created_at"],
            },
        ),
    ]
