# Generated by Django 5.2.6 on 2025-10-14 05:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0004_notification_remove_productreportlost_product_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='foundproduct',
            name='product',
        ),
        migrations.RemoveField(
            model_name='matchresult',
            name='found_product',
        ),
        migrations.RemoveField(
            model_name='lostproduct',
            name='product',
        ),
        migrations.RemoveField(
            model_name='matchresult',
            name='lost_product',
        ),
        migrations.DeleteModel(
            name='Notification',
        ),
        migrations.RemoveField(
            model_name='routemap',
            name='product',
        ),
        migrations.DeleteModel(
            name='FoundProduct',
        ),
        migrations.DeleteModel(
            name='LostProduct',
        ),
        migrations.DeleteModel(
            name='MatchResult',
        ),
        migrations.DeleteModel(
            name='RouteMap',
        ),
    ]
