# Generated by Django 5.2.7 on 2025-10-16 17:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0005_remove_foundproduct_product_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=100)),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Product Notification',
                'verbose_name_plural': 'Product Notifications',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FoundProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reporter_name', models.CharField(max_length=100)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='found_product_images/')),
                ('reporter_contact', models.CharField(max_length=100)),
                ('report_date', models.DateTimeField(auto_now_add=True)),
                ('additional_info', models.TextField(blank=True, null=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='found_reports', to='Product.product')),
            ],
            options={
                'verbose_name': 'Product Found Report',
                'verbose_name_plural': 'Product Found Reports',
                'ordering': ['-report_date'],
            },
        ),
        migrations.CreateModel(
            name='LostProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reporter_name', models.CharField(max_length=100)),
                ('reporter_contact', models.CharField(max_length=100)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='lost_product_images/')),
                ('report_date', models.DateTimeField(auto_now_add=True)),
                ('additional_info', models.TextField(blank=True, null=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lost_reports', to='Product.product')),
            ],
            options={
                'verbose_name': 'Product Lost Report',
                'verbose_name_plural': 'Product Lost Reports',
                'ordering': ['-report_date'],
            },
        ),
        migrations.CreateModel(
            name='MatchResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lost_embedding', models.BinaryField(blank=True, null=True)),
                ('found_embedding', models.BinaryField(blank=True, null=True)),
                ('similarity_score', models.FloatField()),
                ('match_status', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('found_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='match_results', to='Product.foundproduct')),
                ('lost_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='match_results', to='Product.lostproduct')),
            ],
            options={
                'verbose_name': 'Product Match Result',
                'verbose_name_plural': 'Product Match Results',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RouteMap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('map_image', models.ImageField(upload_to='route_maps/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='route_maps', to='Product.product')),
            ],
            options={
                'verbose_name': 'Product Route Map',
                'verbose_name_plural': 'Product Route Maps',
                'ordering': ['-created_at'],
            },
        ),
    ]
