# Generated by Django 5.2.7 on 2025-10-14 01:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AImodels",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="FoundProduct",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField()),
                ("date_found", models.DateField()),
                ("location_found", models.CharField(max_length=255)),
                ("contact_info", models.CharField(max_length=255)),
                (
                    "image",
                    models.ImageField(
                        blank=True, null=True, upload_to="found_products/"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="LostProduct",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField()),
                ("date_lost", models.DateField()),
                ("location_lost", models.CharField(max_length=255)),
                ("contact_info", models.CharField(max_length=255)),
                (
                    "image",
                    models.ImageField(
                        blank=True, null=True, upload_to="lost_products/"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="Notification",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("user_contact", models.CharField(max_length=255)),
                ("message", models.TextField()),
                ("sent_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="MatchResult",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("match_score", models.FloatField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "found_product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="AI.foundproduct",
                    ),
                ),
                (
                    "lost_product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="AI.lostproduct"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="RouteMap",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("route_data", models.JSONField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "found_product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="AI.foundproduct",
                    ),
                ),
                (
                    "lost_product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="AI.lostproduct"
                    ),
                ),
            ],
        ),
    ]
