# Generated by Django 5.2.7 on 2025-10-16 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AI', '0002_aimodels_foundproduct_contact_info_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='matchresult',
            name='timestamp',
        ),
        migrations.RemoveField(
            model_name='routemap',
            name='product',
        ),
        migrations.AlterField(
            model_name='aimodels',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='foundproduct',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='lostproduct',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='matchresult',
            name='similarity_score',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
